#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/bicleaner-ai-classify
}

depends() {
	echo python kenlm
}

install() {
	python3 -m pip install -U --force-reinstall bicleaner-ai tensorflow==2.3.2 psutil
}

