#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/bleualign_cpp
}

depends() {
	echo boost
}

install() {
	pushd bleualign-cpp

	git submodule update --init
	mkdir -p build && cd build
	cmake .. \
		-DCMAKE_INSTALL_PREFIX=$PREFIX \
		-DCMAKE_BUILD_TYPE=Release
	make -j8 bleualign_cpp
	cp bleualign_cpp $PREFIX/bin/
	popd
}

