#!/bin/bash

is-installed() {
	test -d $PREFIX/include/boost
}

depends() {
	echo env icu4c python
}

install() {
	test -d boost_1_74_0 || curl -L https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.tar.gz | tar -zx
	pushd boost_1_74_0
	rm -rf build
	./bootstrap.sh --prefix=$PREFIX
	./b2 \
		--without-mpi \
		--without-graph_parallel \
		--build-dir=build \
		install
	popd
}

