#!/bin/bash

is-installed() {
	test -d $PREFIX/include/gperftools
}

install() {
	VERSION=2.9.1

	test -d gperftools-$VERSION || curl -L "https://github.com/gperftools/gperftools/releases/download/gperftools-${VERSION}/gperftools-${VERSION}.tar.gz" | tar -zx

	pushd gperftools-$VERSION

	./configure --prefix $PREFIX
	
	# Patch the makefile to not use `cp -p` because `-p` wont work on CSD3
	cat Makefile | sed 's,\bcp -p\b,cp,g' > Makefile.patched
	
	make -f Makefile.patched -j8
	make -f Makefile.patched install

	popd
}

