#!/bin/bash

install() {
	test -d hunspell-1.7.0 || curl -L 'https://github.com/hunspell/hunspell/archive/refs/tags/v1.7.0.tar.gz' | tar -xz
	pushd hunspell-1.7.0
	autoreconf -vfi
	./configure --prefix=$PREFIX
	make -j8
	make install
	popd

	# Debian package hunspell as "libhunspell" while hunspell
	# itself always adds a version number to its library?
	# Anyway this confuses the hunspell python package, so
	# we just symlink it without a version number as an alias.
	pushd $PREFIX/include
	for ext in a la so; do
		ln -s libhunspell-1.7.${ext} libhunspell.${ext}
	done
	popd
}

depends() {
	echo env
}

is-installed() {
	test -x $PREFIX/bin/hunspell
}

