#!/bin/bash

is-installed() {
	#test -f $PREFIX/include/unicode/utf8.h

	# Just test whether there is some version available
	type -P icu-config > /dev/null
}

install() {
	test -d icu|| curl -L "https://github.com/unicode-org/icu/releases/download/release-68-2/icu4c-68_2-src.tgz" | tar -xz
	
	pushd icu/source

	./configure --prefix=$PREFIX --disable-samples --disable-tests --enable-static --with-library-bits=64
	make -j8
	make install
	
	popd
}
