#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/lmplz
}

depends() {
	echo python
}

install() {
	pushd kenlm

	mkdir -p build && cd build

	module load eigen/latest
	cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX
	make -j8 install

	pip3 install .. --config-settings="--build-option=--max_order=7"
	popd
}
