#!/bin/bash
# CSD3 is misbehaving a bit and the python/3.8 module is
# providing the headers for liblzma. However it doesn't
# find the liblzma.so file in the Python/3.8 module so
# it ends up linking against the so file in /lib64, which
# isn't compatible with the header files from Python/3.8.
# This work-around just copies the headers into our own
# prefix which has priority over all other files. But
# it is only necessary on CSD3. On Cirrus everything seems
# to be okay.

is-installed() {
	if [[ "$(hostname -A)" =~ "hpc.cam.ac.uk" ]]; then
		test -f $PREFIX/include/lzma.h
	else
		true
	fi
}

depends() {
	echo env
}

install() {
	ln -fs /usr/local/software/spack/current/opt/spack/linux-rhel7-x86_64/gcc-7.2.0/xz-5.2.4-v7gjh3hab2muhuen2qgqmcczo5gogxtk/include/* $PREFIX/include
	ln -fs /usr/local/software/spack/current/opt/spack/linux-rhel7-x86_64/gcc-7.2.0/xz-5.2.4-v7gjh3hab2muhuen2qgqmcczo5gogxtk/lib/liblzma.* $PREFIX/lib/
}
