#!/bin/bash

depends() {
	echo gperftools protobuf boost
}

is-installed() {
	test -x $PREFIX/bin/marian-decoder-cpu
}

install() {
	pushd marian-fbgemm/

	git submodule update --init --recursive

	mkdir -p build && cd build

	cmake ..\
		-DCMAKE_INSTALL_PREFIX=$PREFIX \
		-DUSE_FBGEMM=ON \
		-DUSE_SENTENCEPIECE=ON \
		-DCOMPILE_CUDA=OFF \
		-DUSE_STATIC_LIBS=ON \
		-DCMAKE_CXX_STANDARD_LIBRARIES="-liconv"

	make -j8 marian_decoder marian_conv
	# make install # bad idea, installs all kinds of libraries

	# Note that make install did not install marian's executables in bin. That's
	# okay, since we'll be needing different versions of marian anyway.
	cp marian-decoder $PREFIX/bin/marian-decoder-cpu
	cp marian-conv $PREFIX/bin/marian-conv

	popd
}

