#!/bin/bash

is-installed() {
	test -s $PREFIX/bin/moses2
}

depends() {
	echo env
}

install() {
	pushd mosesdecoder
	
	BOOST_BUILD_PATH=jam-files/boost-build \
	./jam-files/bjam -j8 \
		-a \
		--with-boost=$PREFIX \
		--prefix=$PREFIX \
		--no-xmlrpc-c \
		install

	popd
}
