#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/merge_sort
}

depends() {
	echo boost icu4c preprocess
}

install() {
	pushd paracrawl

	mkdir -p build && cd build

	cmake .. \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=$PREFIX
	make -j8
	cp bin/* $PREFIX/bin/

	popd
}
