#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/cache
}

depends() {
	echo boost
}

install() {
	pushd preprocess

	mkdir -p build && cd build

	cmake .. \
		-DCMAKE_INSTALL_PREFIX=$PREFIX
	make -j8
	cp bin/* $PREFIX/bin/

	popd
}
