#!/bin/bash

install() {
	test -d Python-3.8.8 || curl -L 'https://www.python.org/ftp/python/3.8.8/Python-3.8.8.tgz' | tar -xz
	pushd Python-3.8.8
	./configure \
		--prefix=$PREFIX \
		--enable-optimizations
	make -j8
	make install
	popd
}

depends() {
	echo env
}

is-installed() {
	test -x $PREFIX/bin/python3
}

