#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/tmxt
}

depends() {
	echo python
}

install() {
	pip install -r tmxt/requirements.txt
	echo "python3 $PREFIX/src/tmxt/tmxt.py \"\$@\"" > $PREFIX/bin/tmxt
	chmod +x $PREFIX/bin/tmxt
}

