#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/warc2text
}

depends() {
	echo boost libzip uchardet
}

install() {
	pushd warc2text

	mkdir -p build && cd build

	cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX
	make -j8 warc2text
	#cp libbleualign_cpp_lib.so $PREFIX/lib/
	#cp warc2text $PREFIX/bin/
	#chrpath -d $PREFIX/bin/bleualign_cpp

	popd
}

