#!/bin/bash

is-installed() {
	test -x $PREFIX/bin/warc2text
}

depends() {
	echo boost libzip uchardet icu4c
}

install() {
	pushd warc2text
	git submodule update --init --recursive

	mkdir -p build && cd build

	CXXFLAGS="-march=native" CFLAGS="-march native" cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release
	make -j8 warc2text
	cp bin/warc2text $PREFIX/bin/

	popd
}

